### ISSUE TITLE
棚卸し機能の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#123]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/124
- [ ] https://github.com/KiizanKiizan/Manene/issues/132
- [ ] https://github.com/KiizanKiizan/Manene/issues/133
- [ ] https://github.com/KiizanKiizan/Manene/issues/134
- [ ] https://github.com/KiizanKiizan/Manene/issues/138
- [ ] https://github.com/KiizanKiizan/Manene/issues/140
- [ ] https://github.com/KiizanKiizan/Manene/issues/141
- [ ] https://github.com/KiizanKiizan/Manene/issues/151
```
