### ISSUE TITLE
アイテムステータス一括更新機能の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#146]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/145
- [ ] https://github.com/KiizanKiizan/Manene/issues/147
- [ ] https://github.com/KiizanKiizan/Manene/issues/148
- [ ] https://github.com/KiizanKiizan/Manene/issues/157
```
