### ISSUE TITLE
廃棄登録機能の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#158]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/159
- [ ] https://github.com/KiizanKiizan/Manene/issues/160
- [ ] https://github.com/KiizanKiizan/Manene/issues/164
- [ ] https://github.com/KiizanKiizan/Manene/issues/165
```
