### ISSUE TITLE
廃棄判定機能の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#183]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/184
- [ ] https://github.com/KiizanKiizan/Manene/issues/185
- [ ] https://github.com/KiizanKiizan/Manene/issues/186
- [ ] https://github.com/KiizanKiizan/Manene/issues/187
```
