### ISSUE TITLE
アイテムサイズ計測機能の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#263]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/264
- [ ] https://github.com/KiizanKiizan/Manene/issues/273
- [ ] https://github.com/KiizanKiizan/Manene/issues/274
- [ ] https://github.com/KiizanKiizan/Manene/issues/275
- [ ] https://github.com/KiizanKiizan/Manene/issues/276
- [ ] https://github.com/KiizanKiizan/Manene/issues/277
- [ ] https://github.com/KiizanKiizan/Manene/issues/278
```
