### ISSUE TITLE
忘れ物登録機能の実装

### ISSUE THREAD

**Issue by ytsumori** [KiizanKiizan/Manene#62]
# 概要
会社に服を管理する棚が多数存在し、それぞれの棚に番号が振られている。服と棚番号は紐づいており、服の場所がどこかを管理することができている。服をレンタルに出したり、服を移動すると棚番号が変更される。今回は服を移動して棚番号を変える機能を実装する。

[IMG_5073 (1)](https://github.com/KiizanKiizan/Manene/assets/105505578/731150a9-20f9-4fd5-973b-0ad95486f987)

[IMG_5072 (1)](https://github.com/KiizanKiizan/Manene/assets/105505578/87ed6223-3cba-4c72-bb98-f3b8885e2a68)

# 要件
* バーコードまたは手入力でitemIdが読み取れる

* 正常にitemIdが取得できると取得したアイテムが一覧に追加される

* アイテムをクリックするとアイテム詳細が表示される

* バーコードまたは手入力でlocationIdが読み取れる

* locationIdを取得したら棚移動の確認ダイアログが表示される。

* 確認でOKを押すと棚移動ができる。

* 棚移動が完了すると「完了しました」というモーダルが表示される

* リクエスト毎(アイテム読み取り、アイテム詳細表示、棚移動)でエラーが起きるとエラー画面が表示される

# デザイン
* 動画

https://github.com/KiizanKiizan/Manene/assets/105505578/868de2f4-8b8a-4714-99d0-fa90391e2a47

* 棚移動初期画面

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/f85ae9e1-7210-463e-a5cc-86e76a534ee1)

* アイテムスキャン/棚スキャン画面

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/9e5c5673-1935-4ddb-9875-23b48348e2d0)
[img](https://github.com/KiizanKiizan/Manene/assets/105505578/cc5447d3-196a-4869-8f90-abe90588e618)

* アイテムスキャン後画面 

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/b41bd0b7-d447-4148-9d3b-175fd17b04a4)

* 棚移動確認画面

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/0b49eebe-da79-4eb6-a1bf-cf37af5a202c)

* アイテム詳細画面

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/ab561287-2326-4ead-87bf-bbb6c44e059d)

* エラーの場合、エラー画面が表示される

# ディレクトリ構成

```
app
  L item_location   # url: /item_location
        L page.tsx
        L layout.tsx
  L components
        L  common
            L barcode
                L BarcodeReader.tsx
            L item
                L ItemDetailCard.tsx
                L ItemMiniCard.tsx
        L item_location
            L ItemLocationContainer.tsx
            L ItemFetcher.tsx
            L ItemDetailFetcher.tsx
            L ItemList.tsx
  L api
      L item-location
          L useItemLocationsItemScan.ts
          L useItemLocationsMove.ts
          L useItemsShow.ts
```
# コンポーネント設計

<img width="991" alt="スクリーンショット 2023-07-31 0 29 24" src="https://github.com/KiizanKiizan/Manene/assets/105505578/6de87bc1-6850-465c-a148-a95fa837767a">

# データフロー
<img width="599" alt="スクリーンショット 2023-07-31 0 22 20" src="https://github.com/KiizanKiizan/Manene/assets/105505578/ab4e37ab-aa3c-47f6-8ea4-a771be31722c">

# page
* **ItemLocationPage(SC)** # url/item_location
```
return <ItemLocationContainer/>
```

# components
* **ItemLocationContainer(CC)**
```
return ({ 
    # itemIdがあるなら<ItemFetcher>をレンダリング
            }
            
      //アイテムリストを表示    
      <itemList >
      
      
      //アイテムを取得するためのバーコードダイアログ
     <Dialog open={isOpenBarcode}>
        <BarcodeReader onScan={itemIdをセットする処理}.../>
     </ Dialog>
     
     //棚番号を取得するためのQRダイアログ
     <Dialog open={isOpenQr}>
        <QrReader onScan={locationIdをセットする処理} ... />
     </Dialog>
     
     //棚移動確認ダイアログ
     <Dialog}>
        棚版:x
        に登録しますか？
     </Dialog>
     
# ページ下部にstickyにしたい
    <>
      <Button onClick={() => # Barcodeダイアログを表示させる処理} >アイテムスキャン</Button>
      <Button disabaled={!items} onClick={() => Qrダイアログを表示させる処理}>棚移動</Button>
    </>
  )
```

itemId、locationId、selectedItemsをstateとして管理し、バーコード、QRコード、isOpenItemDetailCard、棚移動確認ダイアログなどのダイアログ系が表示されているかどうかの状態も管理する。

useItemLocationsMove()を使用したclick関数を作成して確認ダイアログに渡す。

* **ItemFetcher(CC)**
バーコードでitemIdを読み取った時にマウントされるコンポーネント。

取得したitemIdを元にuseItemLocationsItemScanを使用してitem情報を取得し、selectedItemsに追加。これによりitemListに表示されるアイテムが増える

```
TProps = {
itemId: number;
selectedItems?: TSelectedItems
onSetItem: () => void
onUnSetItemId: () => void
}
```

```
  const {data, isLoading , error} = useItemLocationsItemScan(itemId)
  onSetItem(...selectedItems, data)
```

* **ItemList(CC)**

バーコードで読み取ったitemの一覧を表示させるコンポーネント。

```
TProps = {
  selectedItems: TSelectedItems[];
  onClickOpenItemDetailCard: () => void
  onClickCloseItemDetailCard: () => void
  isOpenItemDetailCard: boolean
}
```

```
selectedItems.map
<ItemMiniCard  ... />
```

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/5261afa7-e24f-4254-a4c9-d2ff92e06a9a)

* **ItemMiniCard.tsx(CC)**

```
TProps = {
Item: TSelectedItem;
onClickOpenItemDetailCard: () => void
onClickCloseItemDetailCard: () => void
isOpenItemDetailCard: boolean
}
```

```
return (
    <Box onClick={onClickOpenItemDetailCard}>
        # ミニアイテムカード作成
    </Box>
    
    {
    isOpenItemDetailCardがtrueならItemDetailFetcherをレンダリング
    }
)
```

[img](https://github.com/KiizanKiizan/Manene/assets/105505578/a66321ee-ca86-4d20-b56d-d87aace399ac)

* **ItemDetailFetcher(CC)**

```
TProps = {
    item: TSelectedItem;
    onClickCloseItemDetailCard: () => void;
}
```

```
const {data, ... } = useItemsShow(item)

    <Dialog isOpen={true} >
        <ItemDetailCard itemInfo={data} ...>
    </Dialog/>
```

useItemsShowを使用してitemの詳細情報を取得

* **ItemDetailCard.tsx(CC)**

```
TProps = {
  itemInfo: TGetItemsShowResponse;
  onClickSwitchItemDetailCard: () => void;
}
```
[img](https://github.com/KiizanKiizan/Manene/assets/105505578/eda386aa-3922-4137-b8e4-d146fdd3d96b)

ブラウザの戻るボタンを無効にしてonClickCloseItemDetailCardに置き換える。

* **BarcodeReaderCC)**
```
TProps = {
    onScan: (Id: number) => void;
    onClickCloseBarcordReader?: () => void;  
}

# QrCodeReader参考に
```

バーコードからカルテIDを取得する。

ブラウザの戻るボタンを無効にしてonClickCloseBarcordReaderに置き換える。

QrCodeReaderの方もオプショナルでonClickCloseQrReaderを受け取るようにする。

# API
**useItemLocationsItemScan**

> item_locations#item_scan

> GET igoue_admin/app_api/item_loactions/item_scan

> アイテムIdからアイテム情報とそのアイテムが存在する棚情報を取得

params

```
{
  itemId: number
}
```

response

```
{
  id: number;
  size: string;
  itemImageUrl: string;
  mCateSmall: {
      id: number;
      name: string;
  }; 
  mLocation: {
      id: number;
      name: string;    
  }
}
```

**useItemsShow**
> items#show

> GET /igoue_admin/app_api/items/:id

> アイテムの詳細情報を取得

params

`:id (url内)`

response

```
type TGetItemsShowResponse = {
  id: number,
  usedCount: number,
  itemCode: string,
  isMarriage: boolean,
  isElasticBand: boolean,
  itemStatus: {
    status: number,
    name: string
  },
  size: string,
  dropSize: {
    id: number,
    name: string
  },
  regDate: string,
  priceTaxIn: number,
  priceRefTaxIn: number,
  shoulder: number,
  bust: number,
  waist: number,
  minWaist: number,
  maxWaist: number,
  hip: number,
  lengthArm: number,
  lengthTop: number,
  lengthWaist: number,
  lengthLeg: number,
  roundNeck: number,
  roundLeg: number,
  roundCalf: number,
  itemImageUrl: string,
  itemOriginalImageUrl: string,
  leeapSize: string,
  tStockingOrderId: number,
  originalSize: number,
  rank: string,
  mCateSmall: {
    id: number,
    name: string
  },
  mBrand: {
    id: number,
    name: string
  },
  mColor: {
    id: number,
    name: string
  },
  mSubColor: {
    id: number,
    name: string
  },
  mPattern: {
    id: number,
    name: string
  },
  mLogo: {
    id: number,
    name: string
  },
  tAdmin: {
    id: number,
    name: string
  },
  mLocation: {
    id: number,
    name: string
  }
};
```

**useItemLocationsMove**

> item_locations#move

> PATCH /igoue_admin/app_api/item_locations/move

> アイテムを特定の棚に移動させる処理

params
```
targetLocationId: number;
itemIds: number[]
```

response

無し

```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/74
- [ ] https://github.com/KiizanKiizan/Manene/issues/78
- [ ] https://github.com/KiizanKiizan/Manene/issues/79
- [ ] https://github.com/KiizanKiizan/Manene/issues/80
- [ ] https://github.com/KiizanKiizan/Manene/issues/81
- [ ] https://github.com/KiizanKiizan/Manene/issues/99
```
