### ISSUE TITLE
アイテム詳細表示の実装

### ISSUE THREAD

**Issue by ryuhei202** [KiizanKiizan/Manene#90]
```[tasklist]
### Tasks
- [ ] https://github.com/KiizanKiizan/Manene/issues/93
- [ ] https://github.com/KiizanKiizan/Manene/issues/96
- [ ] https://github.com/KiizanKiizan/Manene/issues/113
- [ ] https://github.com/KiizanKiizan/Manene/issues/117
- [ ] https://github.com/KiizanKiizan/Manene/issues/118
```

**Comment by ryuhei202** [comment]
# 概要
レンタルするための洋服の詳細情報を表示する。

# 要件
* アイテムIDからアイテムの詳細画面を表示することができる。

* アイテム詳細をモーダルとして表示することができる。

* バーコードまたは手入力でitemIdを取得できる

# デザイン
**動画**

https://github.com/KiizanKiizan/Manene/assets/105505578/38fc590e-bb93-47ce-a166-03b02aa7e5a9

* **itemID取得画面**

<img width="400" alt="スクリーンショット 2023-08-03 15 03 51" src="https://github.com/KiizanKiizan/Manene/assets/105505578/957374aa-4f44-4c78-bfef-0c4b466ba474">

* **ローディング画面**

<img width="401" alt="スクリーンショット 2023-08-03 15 04 13" src="https://github.com/KiizanKiizan/Manene/assets/105505578/d4815203-5713-495b-8c04-82663922fc40">


* **アイテム詳細画面**
<img width="398" alt="スクリーンショット 2023-08-03 15 04 22" src="https://github.com/KiizanKiizan/Manene/assets/105505578/9e08f144-8dc9-4181-8e6b-2f455e25cc06">

# ディレクトリ構成
```
app
  L item_detail   # url: /item_detail
        L page.tsx
        L [id]     # url: /item_detail/id
            L page.tsx
  L components
        L common
            L item
               L item_detail_card.tsx
        L item_detail
            L item_detail-container.tsx
   L api
      L item_detail
            L getItemsShow.ts
```

# Page
* **ItemDetailPage(SC)**
```
return <ItemDetailContainer/>
```
/item_detail

初期画面でバーコード画面を表示し、itemIdを取得できたら/item_detail/idへ遷移
* **ItemDetailShow(SC)**
```
TProps = {
  params: { id: number };
};
```
```
const ItemDetailData = await getCoordePickIndex(id)

return <itemDetailCard itemInfo={ItemDetailData} />
```
/item_detail/id

getCoordePickIndexを使用してアイテム詳細情報を取得する。

# component
* **ItemDetailContainer(CC)**
```
return <BarcordReader onScan={/item_detail/idへ}
```

* **ItemDetailCard(CC)**
```
TProps = {
itemInfo: TGetItemsShowResponse
}
```
MUIとitemInfoをでデザイン通りのカードを実装する

# API
* **getItemsShow.ts**
> items#show

> GET /igoue_admin/app_api/items/:id

> アイテムの詳細情報を取得するためのSC data fetching関数

params

`:id `(url内)

response
```
type TGetItemsShowResponse = {
  id: number,
  usedCount: number,
  itemCode: string,
  isMarriage: boolean,
  isElasticBand: boolean,
  itemStatus: {
    status: number,
    name: string
  },
  size: string,
  dropSize: {
    id: number,
    name: string
  },
  regDate: string,
  priceTaxIn: number,
  priceRefTaxIn: number,
  shoulder: number,
  bust: number,
  waist: number,
  minWaist: number,
  maxWaist: number,
  hip: number,
  lengthArm: number,
  lengthTop: number,
  lengthWaist: number,
  lengthLeg: number,
  roundNeck: number,
  roundLeg: number,
  roundCalf: number,
  itemImageUrl: string,
  itemOriginalImageUrl: string,
  leeapSize: string,
  tStockingOrderId: number,
  originalSize: number,
  rank: string,
  mCateSmall: {
    id: number,
    name: string
  },
  mBrand: {
    id: number,
    name: string
  },
  mColor: {
    id: number,
    name: string
  },
  mSubColor: {
    id: number,
    name: string
  },
  mPattern: {
    id: number,
    name: string
  },
  mLogo: {
    id: number,
    name: string
  },
  tAdmin: {
    id: number,
    name: string
  },
  mLocation: {
    id: number,
    name: string
  }
};
```
